carts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.cart, name="carts"),
    url(r'^api/refresh$', views.cart_detail_api_view, name="cart-api"),
    url(r'^checkout$', views.checkout, name="checkout"),
    url(r'^checkout/success$', views.checkout_complete, name="checkout-success"),
    url(r'^update$', views.cart_update, name="update"),
]

furnitures/urls.py
from django.conf.urls import url

# from graphene_django.views import GraphQLView
from . import views

urlpatterns = [
    # url(r'^furnitures', views.FurnitureListView.as_view(), name="list-furnitures"),
    url(r'^furnitures', views.furnitures, name="furnitures"),
    url(r'^search/autocomplete/$', views.autocomplete, name="autocomplete"),
    url(r'^find/', views.FacetedSearchView.as_view(), name='haystack_search'),
    url(r'^furniture/(?P<slug>[\w-]+)', views.furniture, name="furniture"),
    url(r'^ajax/furniture', views.ajax_furniture_detail, name="ajax-furniture-detail"),
    url(r'^categories', views.CategoryListView.as_view(), name="list-categories"),
    url(r'^category/(?P<hierarchy>.+)', views.show_product_on_category, name='product-category'),
    # url(r'^graphql', GraphQLView.as_view(graphiql=True)),
]

personalizedFurniture/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt

# from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from graphene_django.views import GraphQLView

from accounts.views import GuestRegisterView
from .views import home

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^', include('furnitures.urls')),
    url(r'^', include('addresses.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^register/guest$', GuestRegisterView.as_view(), name="guest_register"),
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^graphql', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    url(r'^api/v1/', include('furnitures.urls', namespace='furnitures-api')),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/token/', obtain_jwt_token, name='api-token'),
    url(r'^api/token/refresh/', refresh_jwt_token),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

furnitures/models.py
import random
import os

from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from mptt.models import MPTTModel, TreeForeignKey
from markdownx.models import MarkdownxField

from personalizedFurniture.utils import unique_slug_generator


class Manufacturer(models.Model):
	"""
	Represents a Manufacturer
	"""
	name = models.CharField(max_length=100, unique=True)
	slug = models.SlugField(max_length=100, unique=True)
	description = models.TextField(null=True, blank=True)
	is_active = models.BooleanField(default=True)
	updated_by = models.CharField(max_length=100)
	updated_on = models.DateTimeField(auto_now=True)
	created_on = models.DateTimeField(auto_now_add=True)
	created_by = models.CharField(max_length=100)

	class Meta:
		ordering = ('name',)

	def __str__(self):
		return self.name

	# def get_absolute_url(self):
	#     return reverse('manufacturer-detail', kwargs={'slug': self.slug})

	def get_breadcrumbs(self):
		"""
		Returns name and url dictionary tuple
		"""
		return ({'name': self.name, 'url': self.get_absolute_url()},)

	@classmethod
	def get_manufacturers(cls):
		"""
		Returns list of active manufacturers
		"""
		return list(cls.objects.filter(is_active=True))

STATUS = (
	('approved', 'Approved'),
	('pending', 'Pending'),
	('rejected', 'Rejected'),
)

def get_filename_ext(filepath):
	base_name = os.path.basename(filepath)
	name, ext = os.path.splitext(base_name)
	return name, ext

def upload_image_path(instance, filename):
	new_filename = random.randint(1,3910209312)
	name, ext = get_filename_ext(filename)
	final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
	return "4nitures/{new_filename}/{final_filename}".format(
			new_filename=new_filename,
			final_filename=final_filename
			)


def upload_furniture_image_path(instance, filename):
	if (instance.parent):
		return '4niture/{0}/{1}'.format(instance.parent.name, instance.name)
	else:
		return '4niture/{0}'.format(instance.name)


def furniture_type_image_path(instance, filename):
	return '4niture/{0}/{1}'.format(instance.name, instance.name)


class Category(MPTTModel):
	name = models.CharField(max_length=100, blank=True, null=True)
	image = models.ImageField(null=True, blank=True,
							  upload_to=upload_furniture_image_path)
	slug = models.SlugField(max_length=200, unique=True)
	parent = TreeForeignKey('self', null=True, blank=True,
							related_name='children', db_index=True)

	class Meta:
		unique_together = (('parent', 'slug',))
		verbose_name_plural = 'Categories'

	class MPTTMeta:
		order_insertion_by = ['name']

	def __str__(self):
		return self.name

	def get_furniture_list(self):
		return Furniture.objects.filter(category=self.slug)

	def get_absolute_url(self):
		return '/'.join([x['slug'] for x in self.get_ancestors(include_self=True).values()])

	def is_second_node(self):
		return True if (self.get_ancestors().count() == 1) else False

	def get_slug_list_for_categories(self):
		try:
			ancestors = self.get_ancestors(include_self=True)
		except:
			ancestors = []
		else:
			ancestors = [i.slug for i in ancestors]
		slugs = []
		for i in range(len(ancestors)):
			slugs.append('/'.join(ancestors[:i + 1]))
		return slugs

	def get_count_children(self):
		return self.get_descendant_count()

class FurnitureQuerySet(models.QuerySet):
	def active(self):
		return self.filter(is_active=True)

	def featured(self):
		return self.active().filter(is_featured=True)

	def new_arrival(self, max_furnitures):
		return self.active().order_by('-id')[:max_furnitures]

	def free_shipping(self, max_furnitures):
		return self.active().filter(is_free_shipping=True)[:max_furnitures]

class FurnitureManager(models.Manager):
	def get_queryset(self):
		return FurnitureQuerySet(self.model, using=self._db)

	def all(self):
		return self.get_queryset().active()

	def featured(self):
		return self.get_queryset().featured()

	def new_arrival(self, max_furnitures):
		return self.get_queryset().new_arrival(max_furnitures)

	def free_shipping(self, max_furnitures):
		return self.get_queryset().free_shipping(max_furnitures)

	def get_by_id(self, slug):
		qs = self.get_queryset().filter(slug=slug)
		if qs.count() == 1:
			return qs.first()
		return None

class Furniture(models.Model):
	name = models.CharField(max_length=100, blank=True, null=True)
	manufacturer = models.ForeignKey(Manufacturer, blank=True, null=True)
	slug = models.SlugField(max_length=200, unique=True)
	sku = models.CharField(max_length=50, verbose_name='SKU', null=True, blank=True)
	gist = models.CharField(
		max_length=500, null=True, blank=True, help_text='Short description of the furniture')
	old_price = models.DecimalField(max_digits=20, decimal_places=2, default=0.0)
	price = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
	quantity = models.PositiveIntegerField(default="0", help_text='Stock quantity')
	content = MarkdownxField()
	note = models.CharField(max_length=500, null=True, blank=True, help_text="Notice on the product")
	meta_info = models.TextField(blank=True, null=True, help_text="Tips or some information related to the product")
	category = models.ForeignKey(Category, null=True, blank=True)
	is_active = models.BooleanField(
	default=True, help_text='Furniture is available for listing and sale')
	is_customizable = models.BooleanField(default=False)
	is_bestseller = models.BooleanField(
		default=False, help_text='It has been best seller')
	is_featured = models.BooleanField(
		default=False, help_text='Promote this furniture on main pages')
	is_free_shipping = models.BooleanField(
		default=False, help_text='No shipping charges')
	timestamp       = models.DateTimeField(auto_now_add=True)
	objects         = FurnitureManager()

	class Meta:
		verbose_name_plural = 'Furnitures'

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('furniture', kwargs={'slug': self.slug})

	def get_discount(self):
		"""
		Return discount on the furniture
		"""
		if self.old_price:
			return int(((self.old_price - self.price) / self.old_price) * 100)
		return 0

	def first_image(self):
		"""
		Return first image of the furniture
		"""
		if self.furniture_pics:
			print(self.furniture_pics.first().image.url)
			return self.furniture_pics.first().image.url
		return 'static/img/4niture.jpg'

	def furniture_total_price(self):
		return self.price * self.quantity

	@classmethod
	def get_active(cls):
		"""
		Returns active furnitures
		"""
		return cls.filter(is_active=True)

	@classmethod
	def featured_furnitures(cls):
		"""
		Returns featured furnitures
		"""
		return list(cls.get_active().filter(is_featured=True))

	@classmethod
	def recent_furnitures(cls, max_furnitures):
		"""
		Returns recent furnitures arrivals
		"""
		return list(cls.get_active().filter(is_active=True).order_by('-id')[:max_furnitures])

class FurniturePic(models.Model):
	"""
	Represents furniture picture
	"""
	furniture = models.ForeignKey(Furniture, related_name='furniture_pics')
	image = models.ImageField(upload_to=upload_image_path)
	display_order = models.IntegerField(default=0)
	created_on = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = 'furnitures_furniture_pic'
		ordering = ('display_order', 'id')
		verbose_name_plural = 'Furniture Pics'

	def __str__(self):
		return '%s [Pic #id %s]' % (self.furniture.name, self.id)
#
#
# class WoodType(models.Model):
#     name = models.CharField(max_length=100, blank=True, null=True)
#     slug = models.SlugField(max_length=200, unique=True)
#     description = models.TextField(blank=True, null=True)
#     image = models.ImageField(null=True, blank=True,
#                               upload_to=furniture_type_image_path)
#     price = models.DecimalField(max_digits=6, decimal_places=2)
#
#     class Meta:
#         verbose_name = 'Type of Wood'
#         verbose_name_plural = 'Type of Woods'
#
#     def __str__(self):
#         return self.name
#
#
# class PolishType(models.Model):
#     name = models.CharField(max_length=100, blank=True, null=True)
#     slug = models.SlugField(max_length=200, unique=True)
#     description = models.TextField(blank=True, null=True)
#     image = models.ImageField(null=True, blank=True,
#                               upload_to=furniture_type_image_path)
#     price = models.DecimalField(max_digits=6, decimal_places=2)
#
#     class Meta:
#         verbose_name = 'Type of Polish'
#         verbose_name_plural = 'Type of Polishes'
#
#     def __str__(self):
#         return self.name
#
#
# class FabricType(models.Model):
#     name = models.CharField(max_length=100, blank=True, null=True)
#     slug = models.SlugField(max_length=200, unique=True)
#     description = models.TextField(blank=True, null=True)
#     image = models.ImageField(null=True, blank=True,
#                               upload_to=furniture_type_image_path)
#     price = models.DecimalField(max_digits=6, decimal_places=2)
#
#     class Meta:
#         verbose_name = 'Type of Fabric'
#         verbose_name_plural = 'Type of Fabrices'
#
#     def __str__(self):
#         return self.name


class CustomDesign(models.Model):
	image = models.ImageField(null=True, blank=True,
							  upload_to='4niture/custom_design/')
	description = models.TextField(blank=True, null=True)

	class Meta:
		verbose_name = 'Custom Design'
		verbose_name_plural = 'Custom Designs'

	def __str__(self):
		return self.image


class VariationCategory(models.Model):
	"""
	A category for furniture variation like Color, Wood Type, Polish Type
	"""
	name = models.CharField(max_length=100, blank=True, null=True)
	slug = models.SlugField(max_length=200, unique=True)
	meta_info = models.CharField(max_length=800, blank=True, null=True)
	updated_on = models.DateTimeField(auto_now=True)
	created_on = models.DateTimeField(auto_now_add=True, null=True)

	def __str__(self):

furnitures/forms.py
from haystack.forms import FacetedSearchForm


class FacetedProductSearchForm(FacetedSearchForm):

    def __init__(self, *args, **kwargs):
        print('data', dict(kwargs.get("data", [])))
        data = dict(kwargs.get("data", []))
        self.categories = data.get('category', [])
        super(FacetedProductSearchForm, self).__init__(*args, **kwargs)

    def search(self):
        sqs = super(FacetedProductSearchForm, self).search()
        if self.categories:
            query = None
            for category in self.categories:
                if query:
                    query += u' OR '
                else:
                    query = u''
                query += u'"%s"' % sqs.query.clean(category)
            sqs = sqs.narrow(u'category_exact:%s' % query)
        return sqs

furnitures/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template import RequestContext
from django.http import JsonResponse
from django.forms.models import model_to_dict
from django.template.loader import render_to_string
from haystack.query import SearchQuerySet

from haystack.generic_views import FacetedSearchView as BaseFacetedSearchView
from rest_framework import generics
from rest_framework import permissions

from .models import Furniture, Category
from carts.models import Cart
from .serializers import CategorySerializer, FurnitureSerializer
from .forms import FacetedProductSearchForm


class CategoryListView(generics.ListAPIView):
    permission_classes = (permissions.AllowAny, )
    serializer_class = CategorySerializer
    queryset = Category.objects.root_nodes()


class FurnitureListView(generics.ListAPIView):
    permission_classes = (permissions.IsAuthenticated, )
    serializer_class = FurnitureSerializer
    queryset = Furniture.objects.all()

def show_pagination(request, obj, num_of_page_to_show):
    paginator = Paginator(obj, num_of_page_to_show)
    page = request.GET.get('page')
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:
        object_list = paginator.page(1)
    except EmptyPage:
        object_list = paginator.page(paginator.num_pages)
    return object_list

def furnitures(request):
    furniture_list = Furniture.objects.all()
    categories = Category.objects.all()
    furnitures = show_pagination(request, furniture_list, 15)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    context = {
        'furnitures': furnitures,
        'categories': categories,
        'cart': cart_obj
    }
    return render(request, 'furnitures/furnitures.html', context)

def ajax_furniture_detail(request):
    furniture_slug = request.GET.get('slug', None)
    qs = Furniture.objects.get(slug=furniture_slug)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    context = {
    'furniture': model_to_dict(qs),
    'cart': model_to_dict(cart_obj),
    'status': 'ok'
    }
    rendered = render_to_string('furnitures/furniture_modal.html', context)
    return JsonResponse({'product_snippet': rendered})

def furniture(request, slug):
    instance = get_object_or_404(Furniture, slug = slug)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    nodes = Category.objects.all()
    # nodes = Category.objects.add_related_count(Category.objects.all(), Furniture, 'category', 'o_count', True)
    context = {
        'furniture': instance,
        'cart': cart_obj,
        'nodes': nodes
    }
    return render(request, 'furnitures/furniture.html', context)

def show_product_on_category(request, hierarchy):
    category_slugs = hierarchy.split('/')
    categories = Category.objects.all()
    furnitures = None
    try:
        category = Category.objects.get(slug=category_slugs[-1]).get_descendants(include_self=True)
        furnitures = Furniture.objects.filter(category__in=category)
    except Category.DoesNotExist:
        print ('should show error in best possible way')
    except Furniture.DoesNotExist:
        furnitures = "No Furniture Exist In This Category"
    context = {
        'furnitures': furnitures,
        'categories': categories
    }
    return render(request, 'furnitures/furnitures.html', context)


def autocomplete(request):
    sqs = SearchQuerySet().autocomplete(
        content_auto=request.GET.get(
            'query',
            ''))[
        :10]
    s = []
    for result in sqs:
        d = {"value": result.name,
            "data": result.object.slug,
            "url": result.object.get_absolute_url()
            }
        s.append(d)
    output = {'suggestions': s}
    return JsonResponse(output)

class FacetedSearchView(BaseFacetedSearchView):

    form_class = FacetedProductSearchForm
    facet_fields = ['category', ]
    template_name = 'search/search_result.html'
    paginate_by = 3
    context_object_name = 'object_list'

templates/furnitures/categories.html
{% block content %}
<div class="text-center"><h2>{{instance.name}}</h2></div>
{% if  instance.children.all %}
  <h4>Sub Categories</h4>
  {% for i in instance.children.all %}
      <a href="{{ i.slug }}"> {{ i.name }} </a><br>
  {% endfor %}

  <br><hr>
{% endif %}

{% if  instance.furniture_set.all %}
{% for i in instance.furniture_set.all %}
<h4>Furnitures</h4>
<div class="row small-up-1 medium-up-3" >

 <div class="column">
  <a href="{{ i.slug }}">
    <div class="card" style="width: 300px; border-color: black">
       <div class="card-divider">
         <strong>{{ i.name | truncatechars:30}}</strong>
       </div>
    </div>
  </a>
 </div>
{% endfor %}

{% endif %}
</div>
{% endblock content %}

templates/furnitures/furniture.html
{% extends 'base.html' %} {% load static namify %} {% block css %} {{block.super}}
<link rel="stylesheet" href="{%static 'css/style-3.css'%}">
<link rel="stylesheet" href="{%static 'css/product-details-1.css'%}"> {% endblock css %} {% block content %}
<section id="product-details">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-12 text-center">
        <!-- bootstrap carousel -->
        <div class="wrapper">
          <div id="carousel-product" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <li data-target="#carousel-product" data-slide-to="0" class="active">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </li>
              <li data-target="#carousel-product" data-slide-to="1">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </li>
              <li data-target="#carousel-product" data-slide-to="2">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </li>
              <li data-target="#carousel-product" data-slide-to="3">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </li>
              <li data-target="#carousel-product" data-slide-to="4">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </li>
            </ol>
            <!-- /Indicators -->
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
              <!-- Carousel 1 -->
              <div class="item active">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </div>
              <!-- /Carousel 1 -->
              <!-- Carousel 2 -->
              <div class="item">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </div>
              <!-- /Carousel 2 -->
              <!-- Carousel 3 -->
              <div class="item">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </div>
              <!-- /Carousel 3 -->
              <!-- Carousel 4 -->
              <div class="item">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </div>
              <!-- /Carousel 4 -->
              <!-- Carousel 5 -->
              <div class="item">
                <img src="{% static 'img/4niture.jpg' %}" alt="themesnerd" class="img-responsive">
              </div>
              <!-- /Carousel 5 -->
            </div>
            <!-- /Wrapper for slides -->
            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-product" role="button" data-slide="prev">
                                <span class="fa fa-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
            <a class="right carousel-control" href="#carousel-product" role="button" data-slide="next">
                                <span class="fa fa-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
            <!-- /Controls -->
          </div>
        </div>
        <!-- /bootstrap carousel -->
      </div>
      <!-- Product Details -->
      <div class="col-md-6 col-sm-12">
        <div class="product-content">
          <a href="#"><span class="product-tag exclusive">Exclusive</span></a>
          <h3 class="product-title"> {{ furniture.name }}</h3>
          <h2 class="product-price"><del>$ 119.99</del><span class="promo-price">$ 90.99</span></h2> {% include 'includes/carts/update-cart.html' with furniture=furniture cart=cart %}
          <div class="product-description">
            <p>When Sadi Ozis first designed the Fishnet chair in Turkey in 1959 it was ahead of its time. Today, its timeless character is evident. Sadi Ozis wove fishnet between the bent tubular steel framework, using innovation due to the lack of available materials due to the Second World War.</p>
            <h4 class="sub-title">Additional Information</h4>
            <p>Sadi’s son Neptun has worked with Walter Knoll on the reissue, featuring an upholstered seat and back. A sculpturual design, authentic and still holding it’s iconic charm.</p>
            <h5 class="sub-title">Materials</h5>
            <p>Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black or highly polished chrome.</p>
            <h5 class="sub-title">Dimensions</h5>
            <p>H 840 x W 660 x D 680 (SH 450) mm.</p>
          </div>
        </div>
      </div>
      <!-- /Product Details -->
    </div>
  </div>
</section>
{% endblock content %} {% block js %} {{block.super}}
<script src="{% static 'js/product-details.js' %}"></script>
{% endblock js %}

templates/furnitures/furniture_modal.html
{% load static %}
<div class="row quick-view product-main">
  <div class="col-sm-6">
    <div class="quick-view-main-image">
      <img src="{% static 'img/slide1.jpg' %}" alt="" class="img-responsive">
    </div>
    <div class="ribbon ribbon-quick-view sale">
      <div class="theribbon">SALE</div>
      <div class="ribbon-background"></div>
    </div>
    <!-- /.ribbon -->
    <div class="ribbon ribbon-quick-view new">
      <div class="theribbon">NEW</div>
      <div class="ribbon-background"></div>
    </div>
    <!-- /.ribbon -->
    <div class="row thumbs">
      <div class="col-xs-4">
        <a href="{% static 'img/slide1.jpg' %}" class="thumb active">
        <img src="{% static 'img/slide1.jpg' %}" alt="" class="img-responsive">
        </a>
      </div>
      <div class="col-xs-4">
        <a href="{% static 'img/slide1.jpg' %}" class="thumb">
        <img src="{% static 'img/slide1.jpg' %}" alt="" class="img-responsive">
        </a>
      </div>
      <div class="col-xs-4">
        <a href="{% static 'img/slide1.jpg' %}" class="thumb">
        <img src="{% static 'img/slide1.jpg' %}" alt="" class="img-responsive">
        </a>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <h2>{{ furniture.name }}</h2>
    <p class="text-muted text-small text-center">
      {{ furniture.gist }}
    </p>
    <div class="box">
      <form>
        <div class="sizes">
          <h3>Available sizes</h3>
          <label for="size_s">
          <a href="#">S</a>
          <input type="radio" id="size_s" name="size" value="s" class="size-input">
          </label>
          <label for="size_m">
          <a href="#">M</a>
          <input type="radio" id="size_m" name="size" value="m" class="size-input">
          </label>
          <label for="size_l">
          <a href="#">L</a>
          <input type="radio" id="size_l" name="size" value="l" class="size-input">
          </label>
        </div>
			</form>
        <p class="price">$124.00</p>
        <p class="text-center">
					{% include 'includes/carts/update-cart.html' with furniture=furniture cart=cart %}
          </button>
        </p>
    </div>
  </div>
  <div class="quick-view-social">
    <h4>Show it to your friends</h4>
    <p>
      <a href="#" class="external facebook" data-animate-hover="pulse"><i class="fa fa-facebook"></i></a>
      <a href="#" class="external gplus" data-animate-hover="pulse"><i class="fa fa-google-plus"></i></a>
      <a href="#" class="external twitter" data-animate-hover="pulse"><i class="fa fa-twitter"></i></a>
      <a href="#" class="email" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
    </p>
  </div>
</div>

templates/furnitures/furnitures.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
	{{block.super}}
	<link rel="stylesheet" href="{%static 'css/furnitures/furnitures.css'%}">
{% endblock css %}

{% block content %}
<section id="furnitures">
  <div class="container">
    <div class="row">
			<div class="col-md-3">
				{% include 'furnitures/includes/categories_sidebar.html' with nodes=categories %}
			</div>
      <div class="col-md-9 col-sm-12">
				<h4><strong>Furnitures</strong></h4>
				<div class="product">
					{% for furniture in furnitures %}
					<div class="product-card">
						<div class="product-image">
							<img src="{{furniture.first_image}}" alt="" />
						</div>
						<div class="product-info">
							<h5>{{ furniture.name }}</h5>
							<h6><del>{{ furniture.old_price }}</del> Rs.{{ furniture.price }}</h6>
						</div>
						<div class="add-to-cart">
							{% include 'includes/carts/update-cart.html' with furniture=furniture cart=cart size="btn-sm"%}
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="col-sm-12">
			{% include 'includes/pagination.html' with obj=furnitures %}
		</div>
	</div>
</section>
{% endblock content %}

{% block js %}
	{{block.super}}
	<script type="text/javascript">
	$(document).ready(function(){
		var productCard = $('.product-card');
    productCard.hover(function(){
        $(this).find('.add-to-cart').addClass('show');
        }, function(){
        $(this).find('.add-to-cart').removeClass('show');
    });
	});
	</script>
{% endblock js %}

templates/furnitures/furnitures_home.html
{% load static %}
<section id="products">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 section-heading-wrap text-center">
                <h2 class="section-heading">New Furniture Arrival</h2>
                <h4 class="section-subheading">Home to the Finest Interior Design Products in the World</h4>
            </div>
        </div>
          {% for furniture in furnitures %}
      		{% if forloop.first %}
					<div class="row">
						{% endif %}
          <div class="col-md-3 col-sm-6 col-xs-12 no-padding">
            <figure class="wow fadeIn">
              {% if furniture.image %}
                <img class="img-responsive" src={{ furniture.image.url }} alt="furniture">
                {% else %}
                <img class="img-responsive" src={% static 'img/4niture.jpg' %} alt="furniture">
                {% endif %}
                <figcaption>
                    <a href="{% url 'furniture' furniture.slug%}">
                        <h5 class="product-title">{{ furniture.name }}</h5>
                        <h4 class="product-price"><del>{{ furniture.old_price}}</del><span class="promo-price">Rs. {{furniture.price}}</span></h4>
                        <p class="product-details">{{ furniture.gist }}</p>
                    </a>
                </figcaption>
            </figure>
					</div>
            {% if forloop.counter|divisibleby:4 %}
					</div>
            <div class="row">{%endif %}
              {% if forloop.last %}
            </div>
      		{% endif %}
      		{% endfor %}
        </div>
    </div>
</section>