carts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.cart, name="carts"),
    url(r'^api/refresh$', views.cart_detail_api_view, name="cart-api"),
    url(r'^checkout$', views.checkout, name="checkout"),
    url(r'^checkout/success$', views.checkout_complete, name="checkout-success"),
    url(r'^update$', views.cart_update, name="update"),
]

personalizedFurniture/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt

# from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token
from graphene_django.views import GraphQLView

from accounts.views import GuestRegisterView
from .views import home

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^', include('furnitures.urls')),
    url(r'^', include('addresses.urls')),
    url(r'^carts/', include('carts.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^register/guest$', GuestRegisterView.as_view(), name="guest_register"),
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^graphql', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    url(r'^api/v1/', include('furnitures.urls', namespace='furnitures-api')),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/token/', obtain_jwt_token, name='api-token'),
    url(r'^api/token/refresh/', refresh_jwt_token),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

addresses/models.py
from django.db import models
from django.core.urlresolvers import reverse

from billing.models import BillingProfile

ADDRESS_TYPES = (
	('billing', 'Billing address'),
	('shipping', 'Shipping address'),
)

class Address(models.Model):
	billing_profile = models.ForeignKey(BillingProfile, blank=True, null=True)
	name            = models.CharField(max_length=120, null=True, blank=True, help_text='Shipping to? Who is it for?')
	nickname        = models.CharField(max_length=120, null=True, blank=True, help_text='Internal Reference Nickname')
	address_type    = models.CharField(max_length=120, choices=ADDRESS_TYPES)
	address_line_1  = models.CharField(max_length=120)
	address_line_2  = models.CharField(max_length=120, null=True, blank=True)
	city            = models.CharField(max_length=120)
	country         = models.CharField(max_length=120, default='Nepal', blank=True, null=True)
	state           = models.CharField(max_length=120)
	postal_code     = models.CharField(max_length=120)

	def __str__(self):
		if self.nickname:
			return str(self.nickname)
		return str(self.address_line_1)

	def get_absolute_url(self):
		return reverse("address-update", kwargs={"pk": self.pk})

	def get_short_address(self):
		for_name = self.name
		if self.nickname:
			for_name = "{} | {},".format( self.nickname, for_name)
		return "{for_name} {line1}, {city}".format(
				for_name = for_name or "",
				line1 = self.address_line_1,
				city = self.city
			)

	def get_address(self):
		return "{for_name}\n{line1}\n{line2}\n{city}\n{state}, {postal}\n{country}".format(
				for_name = self.name or "",
				line1 = self.address_line_1,
				line2 = self.address_line_2 or "",
				city = self.city,
				state = self.state,
				postal= self.postal_code,
				country = self.country
			)

billing/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save

from accounts.models import GuestEmail

User = settings.AUTH_USER_MODEL

class BillingProfileManager(models.Manager):
	def new_or_get(self, request):
		guest_email_id = request.session.get('guest_email_id')
		user = request.user
		created = False
		billing_profile = None
		if user.is_authenticated():
			'''
			logged in user checkout
			'''
			billing_profile, created = self.model.objects.get_or_create(user=user, email=user.email)
		elif guest_email_id is not None:
			'''
			guest user checkout
			'''
			guest_email_obj = GuestEmail.objects.get(id=guest_email_id)
			billing_profile, created = self.model.objects.get_or_create(email=guest_email_obj.email)
		else:
			pass
		return billing_profile, created


class BillingProfile(models.Model):
	user = models.OneToOneField(User, unique=True, blank=True, null=True)
	email = models.EmailField()
	is_active = models.BooleanField(default=True)
	update = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now_add=True)
	objects   = BillingProfileManager()

	def __str__(self):
		return self.email


def user_created_receiver(sender, instance, created, *args, **kwargs):
    if created:
        BillingProfile.objects.get_or_create(User=instance)
post_save.connect(user_created_receiver, sender=User)

carts/models.py
from decimal import Decimal

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save, m2m_changed

from furnitures.models import Furniture

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj=True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True)
    furnitures = models.ManyToManyField(Furniture, blank=True)
    sub_total = models.DecimalField(default=0.0, max_digits=100, decimal_places=2)
    total = models.DecimalField(default=0.0, max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        furnitures = instance.furnitures.all()
        total = 0
        for x in furnitures:
            total += x.price
        if instance.sub_total != total:
            instance.sub_total = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.furnitures.through)

def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.sub_total > 0:
        instance.total = Decimal(instance.sub_total) * Decimal(1.08) # 8% tax
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

billing/views.py
from django.shortcuts import render

# Create your views here.

carts/views.py
from django.shortcuts import render, redirect
from django.forms.models import model_to_dict
from django.http import JsonResponse
from allauth.account.forms import LoginForm

from .models import Cart
from orders.models import Order
from billing.models import BillingProfile
from furnitures.models import Furniture
from accounts.models import GuestEmail
from accounts.forms import GuestForm
from addresses.forms import AddressForm, AddressCheckoutForm
from addresses.models import Address

def cart(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	login_form = LoginForm(request=request)
	guest_form = GuestForm(request=request)
	context = {
		"cart": cart_obj,
		"login_form": login_form,
		"guest_form": guest_form,
	}
	return render(request, 'carts/cart.html', context)

def cart_detail_api_view(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	products = [{
			"id": x.id,
			"url": x.get_absolute_url(),
			"name": x.name,
			"price": x.price,
			"quantity": x.quantity,
			"image": x.first_image(),
			"furniture_total_price": x.furniture_total_price(),
			}
			for x in cart_obj.furnitures.all()]
	cart_data  = {"products": products, "subtotal": cart_obj.sub_total, "total": cart_obj.total}
	return JsonResponse(cart_data)

def cart_update(request):
	furniture_id = request.POST.get('furniture_id')
	if furniture_id is not None:
		try:
			furniture_obj = Furniture.objects.get(id=furniture_id)
		except Furniture.DoesNotExist:
			return redirect("carts")
		cart_obj, new_obj = Cart.objects.new_or_get(request)
		if furniture_obj in cart_obj.furnitures.all():
			cart_obj.furnitures.remove(furniture_obj)
			added = False
		else:
			cart_obj.furnitures.add(furniture_obj)
			added = True
		request.session['cart'] = cart_obj.furnitures
		request.session['cart_items'] = cart_obj.furnitures.count()
		if request.is_ajax():
			json_data = {
				"added": added,
				"removed": not added,
				"cartItemCount": cart_obj.furnitures.count()
			}
			return JsonResponse(json_data, status=200)
	return redirect("carts")

def checkout(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.furnitures.count() == 0:
		return redirect('carts')
	login_form = LoginForm(request=request)
	guest_form = GuestForm(request=request)
	address_form = AddressCheckoutForm()
	guest_email_id = request.session.get('guest_email_id')
	billing_address_id = request.session.get("billing_address_id", None)
	shipping_address_id = request.session.get("shipping_address_id", None)
	billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
	if billing_profile is not None:
		order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
		if shipping_address_id:
			order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
			del request.session["shipping_address_id"]
		if billing_address_id:
			order_obj.billing_address = Address.objects.get(id=billing_address_id)
			del request.session["billing_address_id"]
		if billing_address_id or shipping_address_id:
			order_obj.save()
	context = {
		"order": order_obj,
		"login_form": login_form,
		"guest_form": guest_form,
		"address_form": address_form,
		"billing_profile": billing_profile
	}
	return render(request, "carts/checkout.html", context)

def checkout_billing(request):
	address_form = AddressCheckoutForm()
	return render(request, "carts/checkout_billing.html", context)

def checkout_shipping(request):
	address_form = AddressCheckoutForm()
	return render(request, "carts/checkout_shipping.html", context)

def checkout_complete(request):
	context = {}
	return render(request, 'carts/checkout_complete.html', context)

templates/carts/checkout/billing.html
<form action='{% if action_url %}{{ action_url }}{% else %}{% url "account_login" %}{% endif %}' method="post">
	{% csrf_token %}
	{% if next_url %}
	<input type='hidden' name='next' value='{{ next_url }}' />
	{% endif %}

	{% if address_type %}
	<input type='hidden' name='address_type' value='{{ address_type }}' />
	{% endif %}
	<div class="row">
		<div class="col-md-6 mb-3">
			<label for="id_nickname">Nickname</label>
			<input type="text" class="form-control" id="id_nickname" name="nickname" placeholder="Nickname" maxlength="120">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_name">Name</label>
			<input type="text" class="form-control" id="id_name" name="name" placeholder="Name" maxlength="120">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_address_line_1">Address Line 1</label>
			<input type="text" class="form-control" id="id_address_line_1" name="address_line_1" placeholder="Address Line 1">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_address_line_2">Address Line 2</label>
			<input type="text" class="form-control" id="id_address_line_2" name="address_line_2" placeholder="Address Line 2">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_city">City</label>
			<input type="text" class="form-control" id="id_city" name="city" placeholder="City">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_state">State</label>
			<input type="text" class="form-control" id="id_state" name="state" placeholder="State">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_postal_code">Postal Code</label>
			<input type="text" class="form-control" id="id_postal_code" name="postal_code" placeholder="Postal Code">
		</div>
	</div>
	<button type="submit" class="btn reg-log-btn">Submit</button>
</form>

templates/carts/checkout/shipping.html
<form action='{% if action_url %}{{ action_url }}{% else %}{% url "account_login" %}{% endif %}' method="post">
	{% csrf_token %}
	{% if next_url %}
	<input type='hidden' name='next' value='{{ next_url }}' />
	{% endif %}

	{% if address_type %}
	<input type='hidden' name='address_type' value='{{ address_type }}' />
	{% endif %}
	<div class="row">
		<div class="col-md-6 mb-3">
			<label for="id_nickname">Nickname</label>
			<input type="text" class="form-control" id="id_nickname" name="nickname" placeholder="Nickname" maxlength="120">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_name">Name</label>
			<input type="text" class="form-control" id="id_name" name="name" placeholder="Name" maxlength="120">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_address_line_1">Address Line 1</label>
			<input type="text" class="form-control" id="id_address_line_1" name="address_line_1" placeholder="Address Line 1">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_address_line_2">Address Line 2</label>
			<input type="text" class="form-control" id="id_address_line_2" name="address_line_2" placeholder="Address Line 2">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_city">City</label>
			<input type="text" class="form-control" id="id_city" name="city" placeholder="City">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_state">State</label>
			<input type="text" class="form-control" id="id_state" name="state" placeholder="State">
		</div>
		<div class="col-md-6 mb-3">
			<label for="id_postal_code">Postal Code</label>
			<input type="text" class="form-control" id="id_postal_code" name="postal_code" placeholder="Postal Code">
		</div>
	</div>
	<button type="submit" class="btn reg-log-btn">Submit</button>
</form>